version: "3.9"

services:
  web:
    build: .
    container_name: fastapi-graphql-app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload